---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment 
  labels:
    type: mysql
    author: advik
spec:
  replicas: 2
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: mysql-pod
      labels:
        type: db
        author: advik
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: advik
...                
