---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: db
    author: advik
spec:
  containers:
    - name: mydb
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: advik
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_STUDY_HARD
          value: mydb
...
