---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    type: appserver
    author: advik
spec:
  replicas: 2
  selector:
    matchLabels:
      type: appserver
  template:
    metadata:
      name: tomcat-pod
      labels:
        type: appserver
    spec:
      containers:
        - name: tomcat
          image: tomcat
      tolerations:
        - key: slave3
          operator: Equal
          value: advik3
          effect: NoSchedule
...
