---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wordpress-daemon
  labels:
    type: mydb
    author: advik
spec:
  selector:
    matchLabels:
      type: mydb
  template:
    metadata:
      name: wordpress-pod
      labels:
        type: mydb
    spec:
      containers:
        - name: wordpress
          image: wordpress
          ports:
            - containerPort: 80
              hostPort: 8080
...
