---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-app-deployment 
  labels:
    type: ghost-app
    author: advik
spec:
  replicas: 2
  selector:
    matchLabels:
      type: ghost-app
  template:
    metadata:
      name: ghost-app-pod
      labels:
        type: ghost-app
    spec:
      containers:
        - name: ghost-app
          image: ghost:2.6-alpine
          env:
            - name: DATABASE_CLIENT
              value: mysql
            - name: DATABASE_CONNECTION_HOST
              value: ghostservice
            - name: DATABASE_CONNECTION_USER
              value: ghostapp
            - name: DATABASE_CONNECTION_PASSWORD
              value: advik
            - name: DATABASE_CONNECTION_DATABASE
              value: ghostdb
...
